### PR TITLE
Bump Nokogiri version

### PR DESCRIPTION
**Pull request by therubymug**

### CODE REVIEW

**Comment by BJClark** [comment]
lolololol that this requires nokogiri ruby is a joke

**Comment by therubymug** [comment]
`actionpack | actionview -> rails-html-sanitizer -> loofah -> nokogiri`

You mean: `Rails` is a joke, right?

**Comment by BJClark** [comment]
@therubymug so this never loads the rails part of this in production. If that's why it's required, I don't think you really need to care. The rails app is just so you can run the tests. It's an engine.

**Comment by BJClark** [comment]
+2

**Pull request merged**
